### ISSUE TITLE
Docker Compose Development environment fails on multiple steps

### ISSUE THREAD

**Issue by mcclone2001** [opensourcepos/opensourcepos#3231]
### Background information

- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Checked [open and closed issues](https://github.com/opensourcepos/opensourcepos/issues?utf8=%E2%9C%93&q=is%3Aissue) and no similar issue was already reported (please make sure you searched!)
- [x] Read [README](https://github.com/opensourcepos/opensourcepos/blob/master/README.md), [WHATS_NEW](https://github.com/opensourcepos/opensourcepos/blob/master/WHATS_NEW.txt), [INSTALL.md](https://github.com/opensourcepos/opensourcepos/blob/master/INSTALL.md) and [UPGRADE](https://github.com/opensourcepos/opensourcepos/blob/master/UPGRADE.txt)
- [x] Read the [FAQ](https://github.com/opensourcepos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP extensions installed)
- [x] Read the [wiki](https://github.com/opensourcepos/opensourcepos/wiki)
- [does not apply] Executed any database upgrade scripts if an upgrade pre 3.0.0 (e.g. database/2.4_to_3.0.sql)
- [x] Aware the installation code is in [bintray](https://bintray.com/jekkos/opensourcepos/opensourcepos/view/files?sort=updated&order=asc#files) (see README), and [GitHub master](https://github.com/opensourcepos/opensourcepos/tree/master) is for [developers only](https://github.com/opensourcepos/opensourcepos/wiki/Development-setup) and therefore not complete nor stable

### Installation information

Using the master branch with no modifications (commit: 2e09cd31)
docker-compose version 1.29.0, build 07737305
Docker version 20.10.5, build 55c4c88
Ubuntu 18 on WSL 2 on windows 10

### Issue / Bug  / Question / New Feature

Following the official [documentation](https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development) found multiple issues and finally was unable to install the docker development environment

## Step 1
```
$ docker run --rm -v $(pwd):/app composer/composer:2.0.7 install
```

Note: Composer image has been updated to PHP8, had to select last image tag (composer:2.0.7) that support PHP7 to avoid this error:
```
  Problem 1
    - Root composer.json requires php ^7.2 but your php version (8.0.7) does not satisfy that requirement.
  Problem 2
    - dompdf/dompdf is locked to version v0.8.6 and an update of this package was not requested.
    - dompdf/dompdf v0.8.6 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 3
    - phar-io/manifest is locked to version 1.0.3 and an update of this package was not requested.
    - phar-io/manifest 1.0.3 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 4
    - phar-io/version is locked to version 2.0.1 and an update of this package was not requested.
    - phar-io/version 2.0.1 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 5
    - phpunit/php-code-coverage is locked to version 6.1.4 and an update of this package was not requested.
    - phpunit/php-code-coverage 6.1.4 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 6
    - phpunit/phpunit is locked to version 7.5.6 and an update of this package was not requested.
    - phpunit/phpunit 7.5.6 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 7
    - sebastian/global-state is locked to version 2.0.0 and an update of this package was not requested.
    - sebastian/global-state 2.0.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
```

## Step 2
This worked ok as stated in the documentation
```
$ docker run --rm -v $(pwd):/app -w /app lucor/php7-cli php bin/install.php translations develop
```

## Step 3
```
$ docker run --rm -it -v $(pwd):/app -w /app digitallyseamless/nodejs-bower-grunt npm install
$ docker run --rm -it -v $(pwd):/app -w /app digitallyseamless/nodejs-bower-grunt bower install
```

Note: had to split the command because I was getting this error
```
$ docker run --rm -it -v $(pwd):/app -w /app digitallyseamless/nodejs-bower-grunt "sh -c npm install && bower install"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "sh -c npm install && bower install": executable file not found in $PATH: unknown.
```

## Step 4
This final error I was unable to solve
```
$ docker run --rm -v $(pwd):/app composer/composer install
$ docker-compose -f docker-compose.dev.yml build
mysql uses an image, skipping
Building ospos
[+] Building 2.7s (10/16)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 38B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/php:7.4-apache                                                  2.3s
 => [ospos  1/10] FROM docker.io/library/php:7.4-apache@sha256:c68c9a2b05a6ff1bfd6ba68d8e72438eae54bf4ec678e7878a  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 118.56kB                                                                              0.1s
 => CACHED [ospos  2/10] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     libicu-dev    0.0s
 => CACHED [ospos  3/10] RUN a2enmod rewrite                                                                       0.0s
 => CACHED [ospos  4/10] RUN docker-php-ext-install mysqli bcmath intl gd                                          0.0s
 => CACHED [ospos  5/10] RUN echo "date.timezone = "${PHP_TIMEZONE}"" > /usr/local/etc/php/conf.d/timezone.ini     0.0s
 => ERROR [ospos  6/10] RUN echo -e “$(hostname -i)t$(hostname) $(hostname).localhost” >> /etc/hosts               0.3s
------
 > [ospos  6/10] RUN echo -e “$(hostname -i)t$(hostname) $(hostname).localhost” >> /etc/hosts:
#9 0.301 /bin/sh: 1: cannot create /etc/hosts: Read-only file system
------
executor failed running [/bin/sh -c echo -e “$(hostname -i)\t$(hostname) $(hostname).localhost” >> /etc/hosts]: exit code: 2
ERROR: Service 'ospos' failed to build
```

I just need some guidance on trying to solve this issue, what is this for ?
```
[ospos  6/10] RUN echo -e “$(hostname -i)t$(hostname) $(hostname).localhost” >> /etc/hosts
```

**Comment by jekkos** [comment]
Thanks for the report. The instructions were out of date. I have updated them. Also pull in latest master it has this last line removed now, as it seemed to be an issue on windows machines.

**Comment by mcclone2001** [comment]
Tried it with the last commit to master but on first step:

```
$ docker run --rm -v $(pwd):/app jekkos/composer install
BusyBox v1.31.1 () multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

        -c      Just copy (default)
        -d      Create directories
        -D      Create leading target directories
        -s      Strip symbol table
        -p      Preserve date
        -o USER Set ownership
        -g GRP  Set group ownership
        -m MODE Set permissions
        -t DIR  Install to DIR
```
it looks like a parameter for the install command is missing

**Comment by jekkos** [comment]
My bad it should be 

```
docker run --rm -v $(pwd):/app jekkos/composer composer install
```

I have updated the docs.

**Comment by mcclone2001** [comment]
Step 1 is working ok now.

This could be something on my end but step 2 still fails with:
```
$ docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower "sh -c npm install && bower install"
Unable to find image 'opensourcepos/node-grunt-bower:latest' locally
latest: Pulling from opensourcepos/node-grunt-bower
03bb6e0d1bb3: Pull complete
5e44284f1b48: Pull complete
401fdc283ed9: Pull complete
37337c64b49f: Pull complete
Digest: sha256:3b708e89e7391ae9c3017a70baa739f526acb594c733280ca3423708af175d9b
Status: Downloaded newer image for opensourcepos/node-grunt-bower:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "sh -c npm install && bower install": executable file not found in $PATH: unknown.
```

Had to do this instead
```
$ docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower npm install
$ docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower bower install
```

but on bower install received this error
```
bower html2canvas#*                                   install html2canvas#1.0.0
bower                                             postinstall grunt default genlicense
bower                                             postinstall Loading "composer.coffee" tasks...
bower                                             postinstall ERROR
bower                                             postinstall >> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
bower                                             postinstall >> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
bower                                             postinstall Loading "composer.coffee" tasks...ERROR
bower                                             postinstall >> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
bower                                             postinstall >> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
bower                                             postinstall (node:104) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
bower                                             postinstall Running "wiredep:task" (wiredep) task
bower                                             postinstall Running "bower_concat:all" (bower_concat) task
bower                                             postinstall >> Can’t detect any .tmp/opensourcepos_bower.js on main files for "bootswatch" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.
bower                                             postinstall File tmp/opensourcepos_bower.js created.
bower                                             postinstall >> Can’t detect any .tmp/opensourcepos_bower.css on main files for "bootswatch" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.
bower                                             postinstall File tmp/opensourcepos_bower.css created.
bower                                             postinstall Running "bowercopy:targetdistjqueryui" (bowercopy) task
bower                                             postinstall public/bower_components/jquery-ui/themes/base/jquery-ui.min.css -> public/dist/jquery-ui/jquery-ui.min.css
bower                                             postinstall Running "bowercopy:targetdistbootswatch" (bowercopy) task
bower                                             postinstall public/bower_components/bootswatch/cerulean/ -> public/dist/bootswatch/cerulean
bower                                             postinstall public/bower_components/bootswatch/cosmo/ -> public/dist/bootswatch/cosmo
bower                                             postinstall public/bower_components/bootswatch/cyborg/ -> public/dist/bootswatch/cyborg
bower                                             postinstall public/bower_components/bootswatch/darkly/ -> public/dist/bootswatch/darkly
bower                                             postinstall public/bower_components/bootswatch/flatly/ -> public/dist/bootswatch/flatly
bower                                             postinstall public/bower_components/bootswatch/fonts/ -> public/dist/bootswatch/fonts
bower                                             postinstall public/bower_components/bootswatch/journal/ -> public/dist/bootswatch/journal
bower                                             postinstall public/bower_components/bootswatch/lumen/ -> public/dist/bootswatch/lumen
bower                                             postinstall public/bower_components/bootswatch/paper/ -> public/dist/bootswatch/paper
bower                                             postinstall public/bower_components/bootswatch/readable/ -> public/dist/bootswatch/readable
bower                                             postinstall public/bower_components/bootswatch/sandstone/ -> public/dist/bootswatch/sandstone
bower                                             postinstall public/bower_components/bootswatch/simplex/ -> public/dist/bootswatch/simplex
bower                                             postinstall public/bower_components/bootswatch/slate/ -> public/dist/bootswatch/slate
bower                                             postinstall public/bower_components/bootswatch/spacelab/ -> public/dist/bootswatch/spacelab
bower                                             postinstall public/bower_components/bootswatch/superhero/ -> public/dist/bootswatch/superhero
bower                                             postinstall public/bower_components/bootswatch/united/ -> public/dist/bootswatch/united
bower                                             postinstall public/bower_components/bootswatch/yeti/ -> public/dist/bootswatch/yeti
bower                                             postinstall Running "bowercopy:targetlicense" (bowercopy) task
bower                                             postinstall LICENSE -> public/license/LICENSE
bower                                             postinstall Running "concat:js" (concat) task
bower                                             postinstall File tmp/opensourcepos.js created.
bower                                             postinstall Running "concat:sql" (concat) task
bower                                             postinstall Warning: Unable to write "database/database.sql" file (Error code: EISDIR). Use --force to continue.
bower                                             postinstall Aborted due to warnings.
bower                                                 ECMDERR Failed to execute "grunt default genlicense", exit code of #3 (node:104) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
```

**Comment by jekkos** [comment]
Ok looks odd. Can you try to remove the buildbox image to see if you have the latest? On travis this command does succeed

```
docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower
    sh -c "npm install && bower install && grunt package"
```

**Comment by mcclone2001** [comment]
Ok, found it, the issue is because in the docs you have this
```
docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower "sh -c npm install && bower install"
```
but this works, as in your comment, check the position of the quotes:
```
docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower sh -c "npm install && bower install && grunt package"
```

nevertheless, it´s still throwing errors on bower, I think the last one is the relevant
```
$ docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower sh -c "npm install && bower install && grunt package"
npm WARN grunt-apigen@0.1.3 requires a peer of grunt@~0.4.5 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-jshint@0.6.5 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-watch@0.5.3 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-license-bower@1.0.1 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-mocha-webdriver@1.2.2 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-wiredep@2.0.0 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.

audited 1011 packages in 4.846s

16 packages are looking for funding
  run `npm fund` for details

found 135 vulnerabilities (31 low, 35 moderate, 67 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
bower ESUDO         Please do not run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using "--allow-root" option
Loading "composer.coffee" tasks...ERROR
>> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
>> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
Loading "composer.coffee" tasks...ERROR
>> Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
>> Please run `npm install --dev coffeescript` to enable loading CoffeeScript.
(node:42) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Running "wiredep:task" (wiredep) task

Running "bower_concat:all" (bower_concat) task
>> Can’t detect any .tmp/opensourcepos_bower.js on main files for "bootswatch" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.
File tmp/opensourcepos_bower.js created.
>> Can’t detect any .tmp/opensourcepos_bower.css on main files for "bootswatch" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.
File tmp/opensourcepos_bower.css created.

Running "bowercopy:targetdistjqueryui" (bowercopy) task
public/bower_components/jquery-ui/themes/base/jquery-ui.min.css -> public/dist/jquery-ui/jquery-ui.min.css

Running "bowercopy:targetdistbootswatch" (bowercopy) task
public/bower_components/bootswatch/cerulean/ -> public/dist/bootswatch/cerulean
public/bower_components/bootswatch/cosmo/ -> public/dist/bootswatch/cosmo
public/bower_components/bootswatch/cyborg/ -> public/dist/bootswatch/cyborg
public/bower_components/bootswatch/darkly/ -> public/dist/bootswatch/darkly
public/bower_components/bootswatch/flatly/ -> public/dist/bootswatch/flatly
public/bower_components/bootswatch/fonts/ -> public/dist/bootswatch/fonts
public/bower_components/bootswatch/journal/ -> public/dist/bootswatch/journal
public/bower_components/bootswatch/lumen/ -> public/dist/bootswatch/lumen
public/bower_components/bootswatch/paper/ -> public/dist/bootswatch/paper
public/bower_components/bootswatch/readable/ -> public/dist/bootswatch/readable
public/bower_components/bootswatch/sandstone/ -> public/dist/bootswatch/sandstone
public/bower_components/bootswatch/simplex/ -> public/dist/bootswatch/simplex
public/bower_components/bootswatch/slate/ -> public/dist/bootswatch/slate
public/bower_components/bootswatch/spacelab/ -> public/dist/bootswatch/spacelab
public/bower_components/bootswatch/superhero/ -> public/dist/bootswatch/superhero
public/bower_components/bootswatch/united/ -> public/dist/bootswatch/united
public/bower_components/bootswatch/yeti/ -> public/dist/bootswatch/yeti

Running "bowercopy:targetlicense" (bowercopy) task
LICENSE -> public/license/LICENSE

Running "concat:js" (concat) task
File tmp/opensourcepos.js created.

Running "concat:sql" (concat) task
Warning: Unable to write "database/database.sql" file (Error code: EISDIR). Use --force to continue.

Aborted due to warnings.
```

**Comment by jekkos** [comment]
Can you check if all containers are stoppped? The database.sql file is mounted in the mysql container. If this one is up and running then you might not be able to write to the file as it could be locked.

**Comment by jekkos** [comment]
I have corrected the docs once more, thanks for the feedback.

**Comment by mcclone2001** [comment]
Hello, sorry for the delay, all containers are stopped, I will repeat the test with a clean installation in case that there might be a permission issue with the files

**Comment by mcclone2001** [comment]
Ok, cloning the project again seemed to be the answer, the build finished successfully.

I followed these steps as in the docs:
```
docker run --rm -v $(pwd):/app jekkos/composer composer install
docker run --rm -v $(pwd):/app -w /app jekkos/composer php bin/install.php translations develop
docker run --rm -it -v $(pwd):/app -w /app opensourcepos/node-grunt-bower sh -c "npm install && bower install"
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml up
```

For what is worth.
I made sure to have visual studio closed.

I executed step 3 twice, on the first run I received this error.
```
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [====================================----] 89%
Received 11444K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar: bunzip error -3
tar: short read

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'tar jxf /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar: bunzip error -3
tar: short read

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
npm WARN grunt-apigen@0.1.3 requires a peer of grunt@~0.4.5 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-jshint@0.6.5 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-watch@0.5.3 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-license-bower@1.0.1 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-mocha-webdriver@1.2.2 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-wiredep@2.0.0 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-07T02_42_32_830Z-debug.log
```

I also had to execute step 4 twice because I got this error:
```
 => ERROR [ospos_dev 2/2] RUN yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo  0.5s
------
 > [ospos_dev 2/2] RUN yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini:
#15 0.507 No releases available for package "pecl.php.net/xdebug"
#15 0.507 install failed
------
executor failed running [/bin/sh -c yes | pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini]: exit code: 1
ERROR: Service 'ospos' failed to build
```

In both cases executing the command again solved the issues.

Thanks a lot for your help @jekkos

**Comment by jekkos** [comment]
Ok good to hear that it worked. Phantomjs will be removed in #3213 .
The xdebug issue seemed to be something transient.

Have fun.
